# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-03 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0002_auto_20180103_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='queueuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'queueuser',
                'verbose_name': '\u961f\u5217\u7528\u6237\u591a\u5bf9\u591a\u5173\u7cfb\u8868',
                'verbose_name_plural': '\u961f\u5217\u7528\u6237\u591a\u5bf9\u591a\u5173\u7cfb\u8868',
            },
        ),
        migrations.CreateModel(
            name='syncqueue',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('describe', models.CharField(max_length=100, verbose_name='\u961f\u5217\u63cf\u8ff0')),
                ('ip', models.GenericIPAddressField(verbose_name='\u6e90\u7aefIP')),
                ('path', models.CharField(max_length=100, verbose_name='\u6e90\u7aef\u8def\u5f84')),
                ('rqusers', models.ManyToManyField(through='demo.queueuser', to=settings.AUTH_USER_MODEL, verbose_name='\u53ef\u76d1\u63a7\u7528\u6237')),
            ],
            options={
                'db_table': 'syncqueue',
                'verbose_name': '\u961f\u5217\u914d\u7f6e\u8868',
                'verbose_name_plural': '\u961f\u5217\u914d\u7f6e\u8868',
            },
        ),
        migrations.AddField(
            model_name='queueuser',
            name='rep_queue_sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.syncqueue'),
        ),
        migrations.AddField(
            model_name='queueuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
